fix psm parse bug
ossrs/srs pull request #3383
Opened 2023-01-16 10:36 UTC by duiniuluantanqin

2023-01-16 13:58 UTC, mapengfei53 requested changes, later dismissed

2023-01-16 13:58 UTC, mapengfei53 commented on trunk/src/kernel/srs_kernel_ps.cpp
> +    uint8_t r1 = stream->read_1bytes();
`srs_error_new(ERROR_GB_PS_HEADER, "invalid marker of 0x%#x", r0);`
This should be `srs_error_new(ERROR_GB_PS_HEADER, "invalid marker of 0x%#x", r1);`.

`TRANS_BY_GPT3`

2023-01-17 01:07 UTC, winlinvip commented on trunk/src/kernel/srs_kernel_ps.cpp
> +    uint8_t r1 = stream->read_1bytes();
```
    //      7bits reserved
    //      1bit marker_bit '1'
```

这个7字节保留，其实是不确定都是0的，可能会是其他的数，所以这里应该要`&0x01`才是marker_bit。

```
if ((r1&0x01) != 0x01)
```

2023-01-17 01:07 UTC, winlinvip commented on trunk/src/kernel/srs_kernel_ps.cpp
> +    if ((r1&0x01) != 0x01) {
```
    //      7bits reserved
    //      1bit marker_bit '1'
```

这个7字节保留，其实是不确定都是0的，可能会是其他的数，所以这里应该要`&0x01`才是marker_bit。

```
if ((r1&0x01) != 0x01)
```

2023-01-17 01:57 UTC, chundonglinlin commented on trunk/src/kernel/srs_kernel_ps.cpp
> +    program_stream_map_version_ = (r0&0x1f);
此处需要format下，括号应该也不需要了。可以加下注视说明以及文档引用。

2023-01-17 02:21 UTC, chundonglinlin commented on trunk/src/kernel/srs_kernel_ps.cpp
> +    uint8_t r0 = stream->read_1bytes();
第一个字节`r0`应该是`current_next_indicator_ `， 第二个字节`r1`应该是`program_stream_map_version_ `

2023-01-17 02:25 UTC, duiniuluantanqin commented on trunk/src/kernel/srs_kernel_ps.cpp
> +    uint8_t r0 = stream->read_1bytes();
不，r0里面，第1位是`current_next_indicator_ ` , 后5位是`program_stream_map_version_ `

2023-01-17 02:27 UTC, duiniuluantanqin commented on trunk/src/kernel/srs_kernel_ps.cpp
> +    program_stream_map_version_ = (r0&0x1f);
嗯，括号删掉了

2023-01-17 04:51 UTC, winlinvip approved these changes

2023-01-17 04:58 UTC, chundonglinlin approved these changes

2023-01-17 05:01 UTC, mapengfei53 approved these changes

2023-01-17 05:01 UTC, merged