remove null-pointer-check
ossrs/srs pull request #3477
Opened 2023-03-22 12:16 UTC by yashwardhan-jyani

Removed the unnecessary NULL pointer checks in trunk/src/core/srs_core.hpp

[https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null](url)

This is my first Pull Request, So if anything's wrong please tell me

2023-03-22 21:01 UTC, elfring requested changes
The commit message can be improved.
* How do you think about to omit hyphens from the subject?
* Would you like to [refer to a previous suggestion in your change description](https://github.com/ossrs/srs/issues/3331 "Proposal from 2022-12-23")?

2023-03-23 13:48 UTC, winlinvip commented
Seems make sense to me, however I wonder if all compiler check the null pointer?

2023-03-23 13:54 UTC, elfring commented
>…, however I wonder if all compiler check the null pointer?

:thought_balloon: Would you like to support any compiler versions which would be standard-incompliant in this technical detail?

2023-03-24 06:16 UTC, xiaozhihong commented
@yashwardhan-jyani 

Thanks for your PR.

Follow the reference, delete nullptr is safe.
https://cplusplus.com/reference/new/operator%20delete/
![image](https://user-images.githubusercontent.com/8449258/227438956-393ffd1c-5bac-4877-b147-b5093c747ac8.png)

https://en.cppreference.com/w/cpp/memory/new/operator_delete
![image](https://user-images.githubusercontent.com/8449258/227438930-a9dcaf13-5323-49db-bd25-cdcdf6b5a627.png)


And I test it with simple code.
```cpp
#include <iostream>

int main()
{
    char* p = NULL;
    delete p;

    return 0;
}
```

It works well. 

Then I gdb the program and find the implement of delete in gcc.
![image](https://user-images.githubusercontent.com/8449258/227440053-70341647-afb4-4036-ab26-8716bc565cda.png)

![image](https://user-images.githubusercontent.com/8449258/227439888-282f9ee0-1240-4065-8f25-afb3facd48f4.png)

Obvious, `operator delete` call std::free, std::free call libc free directly, and `man 3 free` tell us
![image](https://user-images.githubusercontent.com/8449258/227440146-17893a44-1d3c-4d17-9e9b-802b6c58102d.png)


But I still have a question, in other platforms which not use gcc, for example, MSVC of Windows, cause the same result? Can you test it? Thanks.

2023-03-24 06:44 UTC, elfring commented
> But I still have a question, …, cause the same result?

How much do you care for standard compliance of applied compiler variants? :thinking:

2023-03-24 09:32 UTC, yashwardhan-jyani commented
@xiaozhihong 

I tried this on MSVC compiler and it's working fine.

![Screenshot 2023-03-24 145526](https://user-images.githubusercontent.com/100014271/227480752-bde70c02-fbd9-4404-bd2f-42608fd36959.jpg)
 


Ignore the errors, it's the intelliSense, i tried to get rid of them but can't seem to do so.
![cx ](https://user-images.githubusercontent.com/100014271/227481440-b2a8d43e-78bd-47d6-96cf-df6a5698079b.jpg)

2023-03-25 02:04 UTC, xiaozhihong approved these changes

2023-03-25 04:08 UTC, winlinvip approved these changes

2023-03-25 04:09 UTC, merged